honeytrap/honeytrap

director/director.go
director/director_linux.go

PR provides resolution to linting errors with the exceptions of the usage of the `md5` crypto package and the error related to mutex copying. 
- Resolve error with `director/` package
- Resolve of error logging
Issue: #16

Resolving Lint errors with director pkg

---

cmd/cmd.go
config/config.go
config/utils.go
director/director_linux.go
providers/container.go
providers/lxccontainer.go
providers/provider.go
providers/utils.go
proxies/agent.go
proxies/conn.go
proxies/events.go
proxies/http/http.go
proxies/listen.go
proxies/proxy.go
proxies/sip/sip.go
proxies/smtp/smtp.go
proxies/ssh/ssh.go
proxies/ssh/ssh_recorder.go
proxies/tcp.go
pushers/events.go
pushers/filters.go
pushers/honeytrap/honeytrap.go
pushers/message/message.go
pushers/pusher.go
server/honeytrap.go
server/ping.go
server/recover.go
server/stats.go

PR adds the new `events` API. It adds basic level calls and adjusts all the provided proxies to include it's instance as to allow future use of the provided instance in reporting events. This will allow us to initially review and adjust the parameters for the event model.
Related to issue #18 
Also #27 , #20

Add New Event API to proxies

---

director/cowriedirector/cowrie.go
director/director.go
director/iodirector/iodirector.go
director/lxcdirector/director_linux.go
server/honeytrap.go

PR updates directors to use a package level store which allows us retrieve a new instance through a given name.

Update director to use package level director store

---

pushers/filters.go

The regex filter function would only check for the first matcher in the config. This fix iterates through the for-loop until a match is found, and return false otherwise.

Fix regex filter function

---

listener/agent/agent.go
listener/agent/conn2.go
listener/agent/connection.go
listener/agent/connections.go
listener/agent/decoder.go
listener/agent/encoder.go
listener/agent/messages.go
server/honeytrap.go

The Honeytrap Agent tunnels traffic through to Honeytrap, allowing quick deployments of simple agents.

Implemented support for Honeytrap Agent

---

listener/agent/connection.go
listener/agent/error.go

This PR implements the `SetReadDeadline()` for the `agentConnection` struct. After the timeout, it will return a timeout error instead of waiting. If no timeout is set, the connection times out after 24 hours.

Add read timeout to AgentConnection

---

director/lxc/lxc.go
director/lxc/lxc_linux.go
director/lxc/lxcconnection.go

This PR adds the housekeeper feature which was lost in a previous merge. 
It starts a goroutine for each container, checking the time it's been idle. When that's more than the set delay, it changes the container status. Idle time updates on every Read and Write to the container, which is possible due to the new wrapped containerconnection struct. 
When a container is stopped, the housekeeper function terminutes, but it's started when the director Dials a container, ensuring there's always a housekeeper running for each running container.
Fixes #129

Lxc container housekeeper

---

cmd/honeytrap/main.go
server/honeytrap.go
server/options.go
storage/storage.go

This PR introduces configurable home dirs. 
Fixes #132 
It adds a CLI flag parameter `-data` or `-d` shorthand and sets that as homedir in the modified `HomeDir` -> `WithHomeDir` function. To allow the `WithToken()` function to use it as well, it's added as a field in the Honeytrap struct. All permission checks are kept intact.

honeytrap: Configurable data directory

---

pushers/file/file.go

Instead of writing to the logfile on every single request, this PR stores messages in a buffer. It writes them when the buffer (500KB) is full or after a second. This should greatly reduce the stress on the hdd in high load situations. 
Buffer size and timeout is up for discussion, not sure what good values are.
Fixes #164

honeytrap: Buffered file writes

---

config.toml.sample
services/ssh/auth.go

The current sample config contains an invalid banner for ssh, resulting in a broken service. The Key field wasn't capitalized so that wasn't working either.
This PR fixes both issues, and should result in ssh-auth working out-of-the-box again
Fixes #171

ssh: fix ssh sample config

---

server/honeytrap.go

This PR fixes peekconnection behaviour, so it occurs only after matching on address. It delays actual peeking until it's neccesary. This should result in less rejected connections before they even reach the service.
Fixes #169

honeytrap: Peek after addr matching

---

config.toml.sample
director/director.go
server/honeytrap.go

This PR adds some information for the user on how to load directors (in `config.toml`) and gives debug information on which directors can be used (in error logs).

Add hints for loading directors

---

services/redis/commands.go
services/redis/messages.go
services/redis/redis.go
services/redis/redis_handler.go

As mentioned in #201, the current Redis implementation is not compatible with Redis clients - it only implements the [inline commands](https://redis.io/topics/protocol#inline-commands), which (as far as I know) isn't widely used.
This PR implements the Redis protocol with a simple parser, but does not support the "inline commands". If needed, it can also be implemented.

Implement Redis protocol

---

Dockerfile

When trying to use the remote config feature from the docker image I got the following error:
```
$ docker run honeytrap/honeytrap --config https://google.com
Get https://google.com: x509: failed to load system roots and no roots provided
```
Seems it needs the CA certs installing. This PR fixes that:
```
andrew@andrew:~/git/honeytrap$ docker run x --config https://mysite.com/config
Honeytrap starting (bae25ufpasn000ea8020)...
Version: 2018-03-04T16:43:25Z (93661d278d0e)
16:46:49.292 honeytrap/server ▶ DEBU 001 Using datadir: /data
..
..
````

Install ca certs so https request will work

---

cmd/honeytrap/main.go

Adds support for `/etc/honeytrap/config.toml`, with the possibility of adding more choices.
Fixes #195, which would then allow for packaging RPMs.

config: support multiple default values

---

Gopkg.lock
services/limiter.go
services/memcached.go
vendor/golang.org/x/time/AUTHORS
vendor/golang.org/x/time/CONTRIBUTING.md
vendor/golang.org/x/time/CONTRIBUTORS
vendor/golang.org/x/time/LICENSE
vendor/golang.org/x/time/PATENTS
vendor/golang.org/x/time/README.md
vendor/golang.org/x/time/rate/rate.go
vendor/golang.org/x/time/rate/rate_go16.go
vendor/golang.org/x/time/rate/rate_go17.go
vendor/golang.org/x/time/rate/rate_test.go

memcached answers can be rate limited, which will record the event, but
limits udp answers

services: memcached: implemented rate limiting for udp answers

---

Gopkg.lock
Gopkg.toml

Removes unused constraints from Gopkg.toml, per `go dep`'s warning.
Note that this also removes the need for https://github.com/honeytrap/namecon, which I guess can be archived if no other projects use it.

honeytrap: remove redundant Gopkg constraints

---

services/ssh/storage.go

This is not an error if DB is new. It will create a new one if there is none.

services/ssh: changed error message on privatekey not present in DB to a Debug message

---

server/honeytrap.go

Fixes #305 and simplifies the service lookup.
I'd like to fix #306 (currently awaiting feedback) in the same PR, so this is not ready for merging.

config: various fixes for ports

---

listener/canary/udp_handlers.go

Was reading through the code and noticed the function documentation was little off in the UDP handler section. I figured I could help fix that pretty easily.
🤷‍♂️ And, yeah, I have a typo in my commit to fix some typo(s). It's like 4 in the morning though.

fix typos in function documentation for the udp handlers

---

server/honeytrap.go
server/honeytrap_test.go

Port numbers are unsigned and go up to 65xxx, yet the parsing in the code was signed. Resulting in an error when trying to use a port number above 32xxx.

Set port parsing to unsigned int for large port numbers

---

server/honeytrap.go
services/services.go

Fixes warnings of unused keys when WithConfig is used.

config: fix parsing in WithConfig

---

config/utils.go
pushers/file/file.go

The `honeytrap.log` file was not being written on my PI 2 model B at all. After some searching, it became clear that it was an issue with the types, since the issue does not occur on a 64 bits machine.
The `defaultWaitTime` was being cast to an `int` value. This type, according to the docs, is [at least an int32](https://golang.org/pkg/builtin/#int). The value in the `defaultWaitTime` is defined as `5 * time.Second`, which is bigger than the max value of the `int32`.

Fix unable to write logfile on 32 bits devices

---

server/options.go

Fixes #287 
The error should only be returned if the folder doesn't exist. When the folder is just created, the error is no longer valid and we can carry on.

Fix the first start by handling missing folder creation correctly

---

storage/storage.go

The key prefix for badger db was not set.
Now it is [prefix].[key]

Storage namespace prefix fix

---

services/smtp/smtp.go

* smtp connections didn't timeout properly, causing the amount
of goroutines to grow

services: smtp: add timeout for smtp connection, closes #387

---

pushers/dshield/config.go
pushers/dshield/dshield.go
pushers/dshield/dshield_test.go
pushers/dshield/messages.go
server/honeytrap.go
services/telnet/telnet.go
services/telnet/terminal.go

the dshield channel will send ssh and telnet authentication attempts
to DShield (https://www.dshield.org/howto.html)

channels: support dshield

---

services/adb.go

Emulates an Android device, exposing a fake shell (todo: implement an actual shell like ssh does?).
To test, `adb connect 127.0.0.1`, then `adb -s 127.0.0.1 shell`.
Fixes #340.

services: add adb

---

server/honeytrap.go

Fix panic when no valid services are defined

---

config/config.go

While writing a config from scratch, I forgot to add a `[[logging]]` section, and was rather puzzled as to why Honeytrap seemed not to start. I think this may occur to other people, so I added a warning when no logging backend is configured.

config: warn if no logging backend

---

director/director.go
listener/options.go
pushers/channel.go
pushers/kafka/kafka_test.go
server/honeytrap.go
web/options.go

Discovered while fixing #402. ~~Not yet ready for merging, I'm waiting for feedback on the issue.~~

Fix WithConfig instances

---

services/telnet/telnet.go
services/telnet/terminal.go

line endings `'\r\n'` were treated wrong `'\r'` was discarded but the `'\n'` stayed in the input buffer.
Also added a newline after `motd`

services/telnet: fix wrong handling of line endings

---

pushers/lumberjack/config.go
pushers/lumberjack/lumberjack.go

- Remove compression level configuration in lumberjack pusher as the impact is negligible with honeytrap message sizes.
- Remove the addition of the @metadata field in results.

Remove index and compression level configuration in lumberjack pusher
